"""
pdf_exporter.py — PDF Shot Breakdown Sheet Exporter for AniPose Pro V3.1.
Generates an HTML/PDF formatted report of poses and animation clips in a folder.
"""

import os
import maya.cmds as cmds


def export_shot_sheet_html(items: list, output_filepath: str, title: str = "AniPose Pro Shot Sheet"):
    """
    Exports a shot breakdown sheet report as HTML/PDF viewable file.
    """
    out_dir = os.path.dirname(output_filepath)
    if out_dir:
        os.makedirs(out_dir, exist_ok=True)

    html_content = f"""<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{title}</title>
    <style>
        body {{ font-family: Arial, sans-serif; background: #0d0f10; color: #f0f2f4; padding: 20px; }}
        h1 {{ color: #d4860a; border-bottom: 2px solid #2a3038; padding-bottom: 10px; }}
        .grid {{ display: flex; flex-wrap: wrap; gap: 20px; margin-top: 20px; }}
        .card {{ background: #161a1d; border: 1px solid #2a3038; border-radius: 8px; width: 200px; padding: 12px; }}
        .card img {{ width: 100%; height: 140px; object-fit: cover; border-radius: 4px; background: #1e2428; }}
        .card .title {{ font-weight: bold; margin-top: 8px; color: #fff; font-size: 14px; }}
        .card .meta {{ font-size: 11px; color: #8b9299; margin-top: 4px; }}
        .badge {{ display: inline-block; padding: 2px 6px; border-radius: 3px; font-size: 10px; background: #3a9e6e; color: #fff; margin-top: 6px; }}
        .badge.clip {{ background: #d4860a; }}
    </style>
</head>
<body>
    <h1>{title}</h1>
    <p>Generated by AniPose Pro V3.1 — {len(items)} items</p>
    <div class="grid">
"""

    for item in items:
        name = item.get("name", "Item")
        itype = item.get("type", "pose").upper()
        author = item.get("author", "Unknown")
        created = item.get("created", "")[:10]
        thumb = item.get("thumbnail", "")
        thumb_src = f"file:///{thumb.replace('\\', '/')}" if thumb else ""

        html_content += f"""
        <div class="card">
            <img src="{thumb_src}" alt="{name}">
            <div class="title">{name}</div>
            <div class="meta">By {author} | {created}</div>
            <div class="badge {'clip' if itype=='CLIP' else ''}">{itype}</div>
        </div>
"""

    html_content += """
    </div>
</body>
</html>
"""

    with open(output_filepath, "w", encoding="utf-8") as f:
        f.write(html_content)

    cmds.inViewMessage(
        amg=f"<hl>Shot Sheet Exported</hl>: Saved to {os.path.basename(output_filepath)}",
        pos="topCenter", fade=True, fadeStayTime=2000
    )
    return output_filepath
